django/core/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    # Custom apps
    path('', include('general.urls')),
    path('data/', include('researchdata.urls')),

    # Django admin
    path('dashboard/', admin.site.urls),

    # Debug Toolbar
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/general/urls.py
from django.urls import path
from django.views.generic import TemplateView

app_name = 'general'
urlpatterns = [
    path('', TemplateView.as_view(template_name="general/coming-soon.html"), name='comingsoon'),
    path('cookies/', TemplateView.as_view(template_name="general/cookies.html"), name='cookies'),
]

django/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Ethical Interface (Coming Soon)</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Roboto:700,900" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        <main role="main" id="main">
            {% block content %}{% endblock %}
        </main>
        <footer role="contentinfo">
            <p>
                <a href="https://www.birmingham.ac.uk/privacy/index.aspx" target="_blank">Privacy</a> |
                <a href="https://www.birmingham.ac.uk/legal/index.aspx" target="_blank">Legal</a> |
                <a href="https://www.birmingham.ac.uk/university/governance/policies-regs/information/index.aspx" target="_blank">Freedom of Information</a> |
                <a href="{% url 'general:cookies' %}">Cookies</a> |
                <a href="https://accessibility.bear.bham.ac.uk/" target="_blank">Accessibility</a>
            </p>
        </footer>

        <!-- JavaScript -->
        <script src="{% static 'js/cookiesmsg.js' %}"></script>
    </body>
</html>